#!/usr/bin/env python3
"""Deploy the static web client to AWS Amplify Hosting.

Uses Amplify's **manual deployment** path: create a deployment, receive a
presigned URL, upload a zip of the site, start the deployment. That requires no
Git connection and no build step, which suits a client that is already plain
HTML, CSS and ES modules — there is nothing to compile, so there is no build to
configure or break.

Usage::

    python scripts/deploy_web.py --region ap-south-1 --api-url https://...
    python scripts/deploy_web.py --region ap-south-1 --app-id d123 --status
"""

import argparse
import datetime as _dt
import io
import json
import os
import subprocess
import sys
import time
import urllib.request
import zipfile
from typing import Any, Dict, List, Optional

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
WEB_DIR = os.path.join(ROOT, "apps", "web")
STATE_FILE = os.path.join(ROOT, ".build", "amplify.json")

BRANCH = "main"
APP_NAME_PREFIX = "scads-web"

# Files never shipped to the public site.
EXCLUDE_NAMES = {".DS_Store", "config.local.js"}
EXCLUDE_DIRS = {"__pycache__", ".git"}


def boto3_or_exit():
    try:
        import boto3  # noqa: WPS433
        return boto3
    except ImportError:
        print("boto3 is required.\n    pip install boto3", file=sys.stderr)
        raise SystemExit(2)


def write_config(api_url: str, environment: str) -> None:
    build = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    content = (
        "/* Generated by scripts/deploy_web.py. Do not edit by hand.\n"
        " *\n"
        " * Nothing secret belongs here: this file is served to every visitor.\n"
        " */\n"
        "window.SCADS_CONFIG = {\n"
        '  apiBaseUrl: "%s",\n'
        '  environment: "%s",\n'
        '  build: "%s"\n'
        "};\n" % (api_url.rstrip("/"), environment, build)
    )
    with open(os.path.join(WEB_DIR, "config.js"), "w", encoding="utf-8") as handle:
        handle.write(content)
    print("  config.js -> %s" % api_url)


def ensure_fixtures() -> None:
    """Generate the demo captures if they are missing.

    The demo panel on the public site fetches these, so shipping without them
    would leave a visibly broken feature on the submitted URL.
    """
    fixtures = os.path.join(WEB_DIR, "fixtures")
    if os.path.isdir(fixtures) and len(os.listdir(fixtures)) > 5:
        return
    print("  generating demo fixtures")
    subprocess.run(
        [sys.executable, os.path.join(ROOT, "scripts", "seed_demo.py"), "--no-fixtures"],
        cwd=ROOT, stdout=subprocess.DEVNULL,
    )
    subprocess.run(
        [sys.executable, os.path.join(ROOT, "scripts", "seed_demo.py")],
        cwd=ROOT, stdout=subprocess.DEVNULL,
    )


def build_zip() -> bytes:
    buffer = io.BytesIO()
    count = 0
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        for root, dirs, files in os.walk(WEB_DIR):
            dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
            for name in sorted(files):
                if name in EXCLUDE_NAMES:
                    continue
                full = os.path.join(root, name)
                archive.write(full, os.path.relpath(full, WEB_DIR))
                count += 1
    payload = buffer.getvalue()
    print("  bundle: %d files, %.1f MB" % (count, len(payload) / 1048576.0))
    return payload


def load_state() -> Dict[str, Any]:
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE, "r", encoding="utf-8") as handle:
            return json.load(handle)
    return {}


def save_state(state: Dict[str, Any]) -> None:
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    with open(STATE_FILE, "w", encoding="utf-8") as handle:
        json.dump(state, handle, indent=2, sort_keys=True)


def ensure_app(amplify, environment: str, app_id: Optional[str]) -> str:
    """Find or create the Amplify app, reusing it across deploys."""
    if app_id:
        return app_id

    state = load_state()
    if state.get("app_id"):
        try:
            amplify.get_app(appId=state["app_id"])
            return state["app_id"]
        except Exception:
            pass

    name = "%s-%s" % (APP_NAME_PREFIX, environment)
    try:
        response = amplify.list_apps(maxResults=100)
        for app in response.get("apps", []):
            if app["name"] == name:
                print("  app: reusing %s (%s)" % (name, app["appId"]))
                return app["appId"]
    except Exception:
        pass

    print("  app: creating %s" % name)
    created = amplify.create_app(
        name=name,
        description="SCADS — counterfeit-medicine risk screening (static client)",
        platform="WEB",
        # No build step: the client is already plain HTML, CSS and ES modules.
        customRules=[
            # SPA-style fallback so a deep link resolves to the app shell rather
            # than a 404, while real assets are served normally.
            {
                "source": "/<*>",
                "target": "/index.html",
                "status": "404-200",
            }
        ],
        environmentVariables={"SCADS_ENV": environment},
    )
    return created["app"]["appId"]


def ensure_branch(amplify, app_id: str) -> None:
    try:
        amplify.get_branch(appId=app_id, branchName=BRANCH)
        return
    except Exception:
        pass
    print("  branch: creating %s" % BRANCH)
    amplify.create_branch(
        appId=app_id,
        branchName=BRANCH,
        description="SCADS static client",
        stage="PRODUCTION",
        enableAutoBuild=False,
    )


def deploy(amplify, app_id: str, payload: bytes) -> str:
    print("  deployment: requesting an upload target")
    created = amplify.create_deployment(appId=app_id, branchName=BRANCH)
    job_id = created["jobId"]

    request = urllib.request.Request(
        created["zipUploadUrl"], data=payload, method="PUT",
        headers={"Content-Type": "application/zip"},
    )
    with urllib.request.urlopen(request, timeout=300) as response:
        if response.status not in (200, 204):
            raise SystemExit("bundle upload returned %s" % response.status)
    print("  deployment: uploaded, starting job %s" % job_id)

    amplify.start_deployment(appId=app_id, branchName=BRANCH, jobId=job_id)
    return job_id


def wait_for_job(amplify, app_id: str, job_id: str, timeout: int = 600) -> str:
    started = time.time()
    last = None
    while time.time() - started < timeout:
        job = amplify.get_job(appId=app_id, branchName=BRANCH, jobId=job_id)
        status = job["job"]["summary"]["status"]
        if status != last:
            print("  deployment: %s" % status)
            last = status
        if status in ("SUCCEED", "FAILED", "CANCELLED"):
            return status
        time.sleep(4)
    return "TIMED_OUT"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--region", default=os.environ.get("AWS_REGION", "ap-south-1"))
    parser.add_argument("--environment", default=os.environ.get("SCADS_ENV", "dev"))
    parser.add_argument("--api-url", default=os.environ.get("SCADS_API_URL"))
    parser.add_argument("--app-id", default=None)
    parser.add_argument("--status", action="store_true", help="report the current URL and exit")
    args = parser.parse_args()

    boto3 = boto3_or_exit()
    amplify = boto3.client("amplify", region_name=args.region)

    if args.status:
        state = load_state()
        app_id = args.app_id or state.get("app_id")
        if not app_id:
            print("no known Amplify app; deploy first", file=sys.stderr)
            return 1
        app = amplify.get_app(appId=app_id)["app"]
        print("app    %s (%s)" % (app["name"], app_id))
        print("url    https://%s.%s" % (BRANCH, app["defaultDomain"]))
        return 0

    if not args.api_url:
        print(
            "--api-url is required (the ApiUrl output from scripts/deploy.py)",
            file=sys.stderr,
        )
        return 2

    print("Deploying the SCADS web client")
    write_config(args.api_url, args.environment)
    ensure_fixtures()
    payload = build_zip()

    app_id = ensure_app(amplify, args.environment, args.app_id)
    ensure_branch(amplify, app_id)
    job_id = deploy(amplify, app_id, payload)
    status = wait_for_job(amplify, app_id, job_id)

    app = amplify.get_app(appId=app_id)["app"]
    url = "https://%s.%s" % (BRANCH, app["defaultDomain"])
    save_state({"app_id": app_id, "branch": BRANCH, "url": url, "api_url": args.api_url})

    print()
    if status != "SUCCEED":
        print("deployment finished in state %s" % status, file=sys.stderr)
        return 1

    print("Web client: %s" % url)
    print()
    print("Next:")
    print("  1. open the URL in a private window and run the three demo packs")
    print("  2. restrict CORS to this origin:")
    print("     python scripts/deploy.py --allowed-origins %s" % url)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
